CONVERT_UI = {
    "convert_frame_row_index": 0, 
    "select_file_button": None, 
    "select_directory_button": None, 
    "file_list_label": None, 
    "file_list_text": None, 
    "clear_paths_button": None, 
    "compression_combobox": None, 
    "compression_combobox_label": None, 
    "color_space_combobox": None, 
    "color_space_combobox_label": None, 
    "bit_rate_scale": None, 
    "bit_rate_scale_label": None, 
    "audio_codec_label": None, 
    "audio_codec_combobox": None, 
    "b_frames_combobox": None, 
    "b_frames_combobox_label": None, 
    "include_text_overlay_label": None, 
    "include_text_overlay_combobox": None, 
    "convert_status_text": None, 
    "convert_button": None, 
}